react_on: тюлень, поставь будильник

help_request: как поставить будильник

responds_on_ok:
    - Да без б!
    - Усё сделано, шеф!
    - Не сцы, не пропустишь!
    - Ок, разбужу... хуем по лбу
    - Всё в ожуре, босс!
    - Слушаюсь и повинуюсь, о великий... гхм
    - Готово, старшой.

responds_on_exception:
    - Иди как ты нахуй, фраерок!
    - Я вас таки не понял.
    - И шо мне прекажете с этим делать??
    - Уупс, что-то пошло не так. Возможно вы долбоёб?
    - В таких условиях я работать отказываюсь!
    - Ты ущемляешь мою индивидуальность!
    - Ты шо, не грамотный ниразу? Там ж написано как нада!
    - Ты втираешь мне какую-то дичь!!
    - И чо ты тут написал?
    - Ой, кто-то знатненько обосрался!
    - Отвали, нахал!
    - Отвали, придурок!
    - Сам себя буди!
    - Телефон будиста подсказать?
    - Пшёл нах!

responds_on_past_alarm:
    - Сорян, машины времени нема =\
    - Кто старое помянит...
    - Это ж при Царе Горохе ещё было!
    - Марти?! О____о
    - В цикличность не умею, сорян =\

responds_on_not_friends:
    - Да ты шо, за спамера меня держишь?! Нахал!
    - Я таких не знаю!
    - Друг моего друга не мой друг!