regexps:
    .*почему.*:
            почему? потому что пошел на хуй, вот почему!
    .*какие.*:
            те самые
    \Aкакой.*:
            большой и толстый
    \Aгде.*:
            в пизде
    .*когда.*:
            да никогда, заебал уже
    \Aчто\Z:
            где когда
    \Aта*к\?*\Z:
            хуяк
    .*мудак.*:
            от мудака слышу!
    .*пидор.*:
            а почему это вас так беспокоит?
    \Aчо*\?*\Z:
            хуй в очо!
    .*бесишь.*:
            хотите поговорить об этом?
    .*ты тупой.*: 
            сам ты тупой, мразина
    \Aну*:
            баранки гну
    капча_с_картинки_.*: 
            ну и глупые же вы.
    .*нахуй.*нуж.*: 
                сам ты нахуй нужен, мразина
    .*ахах.*: 
                ахахахуел, гиена
    
    (?=.*маша.*)(?=.*старая.*): 
                ты чо ахуел мразина очко твое старое
    
    .*марвел.*:
                даже реклама нивеи лучше фильмов марвела
    
    .*похлопаем.*:
                ( ´◔ ω◔`) ノシ

    .*300.*: 
                сколько сколько?
    
    .*СНОУ В КОРОЛИ.*: 
                чтобы он сосал хуи!
                
    .*сноу(?!.*в короли):
                сноу - плоский персонаж, скучный и неинтересный.
                    
    .*член.жпг.*:
                Мне кажется, у кого то проблемы с личной жизнью.
    
    .*хуй.жпг.*:
                Я смотрю у вас все по фрейду.
    
    .*пизда.жпг.*: 
                У тебя проблемы в личной жизни?

    .*доту.*: 
            лучше бы ты в пукан долбился, чем в дoту играл
                    
    .*бот .*: |       
            >>бот
            следи за языком, мудила"

    .*дота.*: 
        лучше бы ты в пукан долбился, чем в дoту играл
    
    .*тристо.*:
               сколько сколько?

    .*триста.*: 
        сколько сколько?
    \bнет\b:
        пидора ответ


in_lines:

    fail: |
            ▄██████████████▄▐█▄▄▄▄█▌
            ██████▌▄▌▄▐▐▌███▌▀▀██▀▀
            ████▄█▌▄▌▄▐▐▌▀███▄▄█▌
            ▄▄▄▄▄██████████████▀
                
    в смысле: 
            хуисле
                
    да: 
            манда
                    
    завали ебало:
            прости пожулуйста
                    
    ты: 
        жопой нюхаешь цветы
       
    и я: 
        свинья?

    привет:
        и тебе               

    ахаха:
        пососи хуйца, гиена
