regexps:
    .*почему.*:
            почему? потому что пошел на хуй, вот почему!
    .*ты тупой.*: 
            сам ты тупой, мразина
    капча_с_картинки_.*: 
            ну и глупые же вы.
    .*нахуй.*нуж.*: 
                сам ты нахуй нужен, мразина
    .*ахах.*: 
                ахахахуел, гиена
    
    (?=.*маша.*)(?=.*старая.*): 
                ты чо ахуел мразина очко твое старое
    
    .*марвел.*:
                даже реклама нивеи лучше фильмов марвела
    
    .*похлопаем.*:
                ( ´◔ ω◔`) ノシ

    .*300.*: 
                сколько сколько?
    
    .*СНОУ В КОРОЛИ.*: 
                чтобы он сосал хуи!
                
    .*сноу(?!.*в короли):
                сноу - плоский персонаж, скучный и неинтересный.
                    
    .*член.жпг.*:
                Мне кажется, у кого то проблемы с личной жизнью.
    
    .*хуй.жпг.*:
                Я смотрю у вас все по фрейду.
    
    .*пизда.жпг.*: 
                У тебя проблемы в личной жизни?

    .*доту.*: 
            лучше бы ты в пукан долбился, чем в дoту играл
                    
    .*бот .*: |       
            >>бот
            следи за языком, мудила"

    .*дота.*: 
        лучше бы ты в пукан долбился, чем в дoту играл
    
    .*тристо.*:
               сколько сколько?

    .*триста.*: 
        сколько сколько?
    \bнет\b:
        пидора ответ


in_lines:

    fail: |
            ▄██████████████▄▐█▄▄▄▄█▌
            ██████▌▄▌▄▐▐▌███▌▀▀██▀▀
            ████▄█▌▄▌▄▐▐▌▀███▄▄█▌
            ▄▄▄▄▄██████████████▀
                
    в смысле: 
            хуисле
                
    да: 
            манда
                    
    завали ебало:
            прости пожулуйста
                    
    ты: 
        жопой нюхаешь цветы
       
    и я: 
        свинья?

    привет:
        и тебе               

    ахаха:
        пососи хуйца, гиена
